name: 'Pull Request Manager'
description: 'GitHub Pull Request Manager'
author: 'Daniel Miller'
branding:
  icon: 'arrow-right-circle'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Checking for dependent PRs
      shell: bash
      run: |
        echo "hello world"

    - name: Post or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: 1
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [milldr/pr-manager][1]

          [1]: https://github.com/milldr/pr-manager
