name: 'Pull Request Manager'
description: 'GitHub Pull Request Manager'
author: 'Daniel Miller'
branding:
  icon: 'arrow-right-circle'
  color: 'red'

runs:
  using: 'composite'
  steps:
    - name: Checking for dependent PRs
      shell: bash
      id: dependencies
      run: |
        echo "blocked-by=\"pr-1\"" > $GITHUB_OUTPUT

    - name: Post or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        body: |
          Dependent Issues
          - ${{ steps.dependencies.outputs.blocked-by }}

          References
          - Created by [milldr/pr-manager][1]

          [1]: https://github.com/milldr/pr-manager
