name: 'Pull Request Manager'
description: 'GitHub Pull Request Manager'
author: 'Daniel Miller'
branding:
  icon: 'arrow-right-circle'
  color: 'red'

inputs:
  token:
    description: "A GitHub token with permission to comment on PRs"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Fetch all open PR comments 
      id: fetch
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: node src/fetch-comments.js

    - name: Checking for dependent PRs
      shell: bash
      id: dependencies
      run: |
        echo "${steps.fetch.outputs.comment-id}"
        echo "blocked-by=\"pr-1\"" > $GITHUB_OUTPUT

    - name: Post or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Dependent Issues
          - ${{ steps.dependencies.outputs.blocked-by }}

          References
          - Created by [milldr/pr-manager][1]

          [1]: https://github.com/milldr/pr-manager

          <!-- DO NOT REMOVE - [managed by milldr/pr-manager] -->
